# .air.toml

# The root directory of your project
root = "."
# A temporary directory for the build
tmp_dir = "tmp"

[build]
# The command to build your application
cmd = "go build -o ./tmp/main ."
# The binary to run after building
bin = "tmp/main"
# Watch these file extensions
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
# Ignore these directories
exclude_dir = ["tmp", "vendor", "node_modules"]
# Log name for the build process
log = "air_build.log"

[proxy]
enabled = true
app_port = 42070 
proxy_port = 42069

[log]
# Show log time
time = true

[color]
# Customize colors for different parts of the output
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

