// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	CarID       pgtype.UUID        `json:"car_id"`
	Datetime    pgtype.Timestamptz `json:"datetime"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Car struct {
	ID                           pgtype.UUID        `json:"id"`
	UserID                       pgtype.UUID        `json:"user_id"`
	RegistrationNumber           string             `json:"registration_number"`
	Make                         pgtype.Text        `json:"make"`
	Colour                       pgtype.Text        `json:"colour"`
	FuelType                     pgtype.Text        `json:"fuel_type"`
	EngineCapacity               pgtype.Int4        `json:"engine_capacity"`
	YearOfManufacture            pgtype.Int4        `json:"year_of_manufacture"`
	MonthOfFirstRegistration     pgtype.Text        `json:"month_of_first_registration"`
	MonthOfFirstDvlaRegistration pgtype.Text        `json:"month_of_first_dvla_registration"`
	TaxStatus                    pgtype.Text        `json:"tax_status"`
	TaxDueDate                   pgtype.Date        `json:"tax_due_date"`
	MotStatus                    pgtype.Text        `json:"mot_status"`
	MotExpiryDate                pgtype.Date        `json:"mot_expiry_date"`
	Co2Emissions                 pgtype.Int4        `json:"co2_emissions"`
	EuroStatus                   pgtype.Text        `json:"euro_status"`
	RealDrivingEmissions         pgtype.Text        `json:"real_driving_emissions"`
	RevenueWeight                pgtype.Int4        `json:"revenue_weight"`
	TypeApproval                 pgtype.Text        `json:"type_approval"`
	Wheelplan                    pgtype.Text        `json:"wheelplan"`
	AutomatedVehicle             pgtype.Bool        `json:"automated_vehicle"`
	MarkedForExport              pgtype.Bool        `json:"marked_for_export"`
	DateOfLastV5cIssued          pgtype.Date        `json:"date_of_last_v5c_issued"`
	ArtEndDate                   pgtype.Date        `json:"art_end_date"`
	DvlaDataFetchedAt            pgtype.Timestamptz `json:"dvla_data_fetched_at"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
}

type TokenBlacklist struct {
	ID            pgtype.UUID        `json:"id"`
	TokenHash     string             `json:"token_hash"`
	UserID        pgtype.UUID        `json:"user_id"`
	Reason        string             `json:"reason"`
	BlacklistedAt pgtype.Timestamptz `json:"blacklisted_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID                       pgtype.UUID        `json:"id"`
	Name                     string             `json:"name"`
	Email                    string             `json:"email"`
	PasswordHash             string             `json:"password_hash"`
	Phone                    string             `json:"phone"`
	IsAdmin                  bool               `json:"is_admin"`
	EmailVerified            bool               `json:"email_verified"`
	EmailVerificationToken   pgtype.Text        `json:"email_verification_token"`
	EmailVerificationExpires pgtype.Timestamptz `json:"email_verification_expires"`
	PasswordResetToken       pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpires     pgtype.Timestamptz `json:"password_reset_expires"`
	PendingEmail             pgtype.Text        `json:"pending_email"`
	EmailChangeToken         pgtype.Text        `json:"email_change_token"`
	EmailChangeExpires       pgtype.Timestamptz `json:"email_change_expires"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}
