// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUserByEmail = `-- name: ActivateUserByEmail :exec
UPDATE users SET email_verified = TRUE WHERE email = $1
`

func (q *Queries) ActivateUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, activateUserByEmail, email)
	return err
}

const adminDeleteAppointment = `-- name: AdminDeleteAppointment :exec
DELETE FROM appointments WHERE id = $1
`

func (q *Queries) AdminDeleteAppointment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteAppointment, id)
	return err
}

const adminDeleteCar = `-- name: AdminDeleteCar :exec
DELETE FROM cars WHERE id = $1
`

func (q *Queries) AdminDeleteCar(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteCar, id)
	return err
}

const blacklistAllUserTokens = `-- name: BlacklistAllUserTokens :exec
INSERT INTO token_blacklist (token_hash, user_id, reason, expires_at)
SELECT
    'user_' || $1::text || '_' || extract(epoch from NOW())::text, -- Generate a placeholder hash for user-wide blacklist
    $1,
    $2,
    $3
WHERE NOT EXISTS (
    SELECT 1 FROM token_blacklist
    WHERE user_id = $1 AND reason = $2 AND blacklisted_at > NOW() - INTERVAL '1 minute'
)
`

type BlacklistAllUserTokensParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Reason    string             `json:"reason"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) BlacklistAllUserTokens(ctx context.Context, arg BlacklistAllUserTokensParams) error {
	_, err := q.db.Exec(ctx, blacklistAllUserTokens, arg.UserID, arg.Reason, arg.ExpiresAt)
	return err
}

const blacklistToken = `-- name: BlacklistToken :exec
INSERT INTO token_blacklist (token_hash, user_id, reason, expires_at) VALUES ($1, $2, $3, $4)
`

type BlacklistTokenParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	Reason    string             `json:"reason"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) BlacklistToken(ctx context.Context, arg BlacklistTokenParams) error {
	_, err := q.db.Exec(ctx, blacklistToken,
		arg.TokenHash,
		arg.UserID,
		arg.Reason,
		arg.ExpiresAt,
	)
	return err
}

const cleanupExpiredTokens = `-- name: CleanupExpiredTokens :exec
DELETE FROM token_blacklist WHERE expires_at <= NOW()
`

func (q *Queries) CleanupExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredTokens)
	return err
}

const confirmEmailChange = `-- name: ConfirmEmailChange :exec
UPDATE users SET email = pending_email, pending_email = NULL, email_change_token = NULL, email_change_expires = NULL, email_verified = TRUE WHERE id = $1
`

func (q *Queries) ConfirmEmailChange(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, confirmEmailChange, id)
	return err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (user_id, car_id, datetime, title, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, car_id, datetime, title, description, status, created_at
`

type CreateAppointmentParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CarID       pgtype.UUID        `json:"car_id"`
	Datetime    pgtype.Timestamptz `json:"datetime"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.UserID,
		arg.CarID,
		arg.Datetime,
		arg.Title,
		arg.Description,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CarID,
		&i.Datetime,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createCar = `-- name: CreateCar :one
INSERT INTO cars (
    user_id,
    registration_number,
    make,
    colour,
    fuel_type,
    engine_capacity,
    year_of_manufacture,
    month_of_first_registration,
    month_of_first_dvla_registration,
    tax_status,
    tax_due_date,
    mot_status,
    mot_expiry_date,
    co2_emissions,
    euro_status,
    real_driving_emissions,
    revenue_weight,
    type_approval,
    wheelplan,
    automated_vehicle,
    marked_for_export,
    date_of_last_v5c_issued,
    art_end_date,
    dvla_data_fetched_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
) RETURNING id, user_id, registration_number, make, colour, fuel_type, engine_capacity, year_of_manufacture, month_of_first_registration, month_of_first_dvla_registration, tax_status, tax_due_date, mot_status, mot_expiry_date, co2_emissions, euro_status, real_driving_emissions, revenue_weight, type_approval, wheelplan, automated_vehicle, marked_for_export, date_of_last_v5c_issued, art_end_date, dvla_data_fetched_at, created_at, updated_at
`

type CreateCarParams struct {
	UserID                       pgtype.UUID        `json:"user_id"`
	RegistrationNumber           string             `json:"registration_number"`
	Make                         pgtype.Text        `json:"make"`
	Colour                       pgtype.Text        `json:"colour"`
	FuelType                     pgtype.Text        `json:"fuel_type"`
	EngineCapacity               pgtype.Int4        `json:"engine_capacity"`
	YearOfManufacture            pgtype.Int4        `json:"year_of_manufacture"`
	MonthOfFirstRegistration     pgtype.Text        `json:"month_of_first_registration"`
	MonthOfFirstDvlaRegistration pgtype.Text        `json:"month_of_first_dvla_registration"`
	TaxStatus                    pgtype.Text        `json:"tax_status"`
	TaxDueDate                   pgtype.Date        `json:"tax_due_date"`
	MotStatus                    pgtype.Text        `json:"mot_status"`
	MotExpiryDate                pgtype.Date        `json:"mot_expiry_date"`
	Co2Emissions                 pgtype.Int4        `json:"co2_emissions"`
	EuroStatus                   pgtype.Text        `json:"euro_status"`
	RealDrivingEmissions         pgtype.Text        `json:"real_driving_emissions"`
	RevenueWeight                pgtype.Int4        `json:"revenue_weight"`
	TypeApproval                 pgtype.Text        `json:"type_approval"`
	Wheelplan                    pgtype.Text        `json:"wheelplan"`
	AutomatedVehicle             pgtype.Bool        `json:"automated_vehicle"`
	MarkedForExport              pgtype.Bool        `json:"marked_for_export"`
	DateOfLastV5cIssued          pgtype.Date        `json:"date_of_last_v5c_issued"`
	ArtEndDate                   pgtype.Date        `json:"art_end_date"`
	DvlaDataFetchedAt            pgtype.Timestamptz `json:"dvla_data_fetched_at"`
}

// Car queries
func (q *Queries) CreateCar(ctx context.Context, arg CreateCarParams) (Car, error) {
	row := q.db.QueryRow(ctx, createCar,
		arg.UserID,
		arg.RegistrationNumber,
		arg.Make,
		arg.Colour,
		arg.FuelType,
		arg.EngineCapacity,
		arg.YearOfManufacture,
		arg.MonthOfFirstRegistration,
		arg.MonthOfFirstDvlaRegistration,
		arg.TaxStatus,
		arg.TaxDueDate,
		arg.MotStatus,
		arg.MotExpiryDate,
		arg.Co2Emissions,
		arg.EuroStatus,
		arg.RealDrivingEmissions,
		arg.RevenueWeight,
		arg.TypeApproval,
		arg.Wheelplan,
		arg.AutomatedVehicle,
		arg.MarkedForExport,
		arg.DateOfLastV5cIssued,
		arg.ArtEndDate,
		arg.DvlaDataFetchedAt,
	)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RegistrationNumber,
		&i.Make,
		&i.Colour,
		&i.FuelType,
		&i.EngineCapacity,
		&i.YearOfManufacture,
		&i.MonthOfFirstRegistration,
		&i.MonthOfFirstDvlaRegistration,
		&i.TaxStatus,
		&i.TaxDueDate,
		&i.MotStatus,
		&i.MotExpiryDate,
		&i.Co2Emissions,
		&i.EuroStatus,
		&i.RealDrivingEmissions,
		&i.RevenueWeight,
		&i.TypeApproval,
		&i.Wheelplan,
		&i.AutomatedVehicle,
		&i.MarkedForExport,
		&i.DateOfLastV5cIssued,
		&i.ArtEndDate,
		&i.DvlaDataFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, phone, is_admin, email_verification_token, email_verification_expires)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, email, password_hash, phone, is_admin, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, pending_email, email_change_token, email_change_expires, created_at
`

type CreateUserParams struct {
	Name                     string             `json:"name"`
	Email                    string             `json:"email"`
	PasswordHash             string             `json:"password_hash"`
	Phone                    string             `json:"phone"`
	IsAdmin                  bool               `json:"is_admin"`
	EmailVerificationToken   pgtype.Text        `json:"email_verification_token"`
	EmailVerificationExpires pgtype.Timestamptz `json:"email_verification_expires"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Phone,
		arg.IsAdmin,
		arg.EmailVerificationToken,
		arg.EmailVerificationExpires,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.PendingEmail,
		&i.EmailChangeToken,
		&i.EmailChangeExpires,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCar = `-- name: DeleteCar :exec
DELETE FROM cars WHERE id = $1 AND user_id = $2
`

type DeleteCarParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCar(ctx context.Context, arg DeleteCarParams) error {
	_, err := q.db.Exec(ctx, deleteCar, arg.ID, arg.UserID)
	return err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM users WHERE email = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteUserByEmail, email)
	return err
}

const getActivePasswordResetToken = `-- name: GetActivePasswordResetToken :one
SELECT password_reset_token, password_reset_expires FROM users WHERE email = $1 AND password_reset_token IS NOT NULL AND password_reset_expires > NOW()
`

type GetActivePasswordResetTokenRow struct {
	PasswordResetToken   pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpires pgtype.Timestamptz `json:"password_reset_expires"`
}

func (q *Queries) GetActivePasswordResetToken(ctx context.Context, email string) (GetActivePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getActivePasswordResetToken, email)
	var i GetActivePasswordResetTokenRow
	err := row.Scan(&i.PasswordResetToken, &i.PasswordResetExpires)
	return i, err
}

const getAllAppointments = `-- name: GetAllAppointments :many
SELECT
  a.id,
  a.user_id,
  a.car_id,
  a.datetime,
  a.title,
  a.description,
  a.status,
  a.created_at,
  u.name AS user_name,
  u.email AS user_email,
  u.phone AS user_phone,
  c.registration_number AS car_registration,
  c.make AS car_make,
  c.colour AS car_colour
FROM appointments a
JOIN users u ON a.user_id = u.id
LEFT JOIN cars c ON a.car_id = c.id
ORDER BY a.created_at DESC
`

type GetAllAppointmentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CarID           pgtype.UUID        `json:"car_id"`
	Datetime        pgtype.Timestamptz `json:"datetime"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UserName        string             `json:"user_name"`
	UserEmail       string             `json:"user_email"`
	UserPhone       string             `json:"user_phone"`
	CarRegistration pgtype.Text        `json:"car_registration"`
	CarMake         pgtype.Text        `json:"car_make"`
	CarColour       pgtype.Text        `json:"car_colour"`
}

func (q *Queries) GetAllAppointments(ctx context.Context) ([]GetAllAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, getAllAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAppointmentsRow
	for rows.Next() {
		var i GetAllAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CarID,
			&i.Datetime,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserPhone,
			&i.CarRegistration,
			&i.CarMake,
			&i.CarColour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAppointmentsByMonth = `-- name: GetAllAppointmentsByMonth :many
SELECT
  a.id, a.user_id, a.car_id, a.datetime, a.title, a.description, a.status, a.created_at,
  c.registration_number AS car_registration,
  c.make AS car_make
FROM appointments a
LEFT JOIN cars c ON a.car_id = c.id
WHERE datetime >= $1 AND datetime < $2
ORDER BY datetime
`

type GetAllAppointmentsByMonthParams struct {
	Datetime   pgtype.Timestamptz `json:"datetime"`
	Datetime_2 pgtype.Timestamptz `json:"datetime_2"`
}

type GetAllAppointmentsByMonthRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CarID           pgtype.UUID        `json:"car_id"`
	Datetime        pgtype.Timestamptz `json:"datetime"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CarRegistration pgtype.Text        `json:"car_registration"`
	CarMake         pgtype.Text        `json:"car_make"`
}

func (q *Queries) GetAllAppointmentsByMonth(ctx context.Context, arg GetAllAppointmentsByMonthParams) ([]GetAllAppointmentsByMonthRow, error) {
	rows, err := q.db.Query(ctx, getAllAppointmentsByMonth, arg.Datetime, arg.Datetime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAppointmentsByMonthRow
	for rows.Next() {
		var i GetAllAppointmentsByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CarID,
			&i.Datetime,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.CarRegistration,
			&i.CarMake,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCarsWithUsers = `-- name: GetAllCarsWithUsers :many
SELECT
    c.id, c.user_id, c.registration_number, c.make, c.colour, c.fuel_type, c.engine_capacity, c.year_of_manufacture, c.month_of_first_registration, c.month_of_first_dvla_registration, c.tax_status, c.tax_due_date, c.mot_status, c.mot_expiry_date, c.co2_emissions, c.euro_status, c.real_driving_emissions, c.revenue_weight, c.type_approval, c.wheelplan, c.automated_vehicle, c.marked_for_export, c.date_of_last_v5c_issued, c.art_end_date, c.dvla_data_fetched_at, c.created_at, c.updated_at,
    u.name AS user_name,
    u.email AS user_email
FROM cars c
JOIN users u ON c.user_id = u.id
ORDER BY c.created_at DESC
`

type GetAllCarsWithUsersRow struct {
	ID                           pgtype.UUID        `json:"id"`
	UserID                       pgtype.UUID        `json:"user_id"`
	RegistrationNumber           string             `json:"registration_number"`
	Make                         pgtype.Text        `json:"make"`
	Colour                       pgtype.Text        `json:"colour"`
	FuelType                     pgtype.Text        `json:"fuel_type"`
	EngineCapacity               pgtype.Int4        `json:"engine_capacity"`
	YearOfManufacture            pgtype.Int4        `json:"year_of_manufacture"`
	MonthOfFirstRegistration     pgtype.Text        `json:"month_of_first_registration"`
	MonthOfFirstDvlaRegistration pgtype.Text        `json:"month_of_first_dvla_registration"`
	TaxStatus                    pgtype.Text        `json:"tax_status"`
	TaxDueDate                   pgtype.Date        `json:"tax_due_date"`
	MotStatus                    pgtype.Text        `json:"mot_status"`
	MotExpiryDate                pgtype.Date        `json:"mot_expiry_date"`
	Co2Emissions                 pgtype.Int4        `json:"co2_emissions"`
	EuroStatus                   pgtype.Text        `json:"euro_status"`
	RealDrivingEmissions         pgtype.Text        `json:"real_driving_emissions"`
	RevenueWeight                pgtype.Int4        `json:"revenue_weight"`
	TypeApproval                 pgtype.Text        `json:"type_approval"`
	Wheelplan                    pgtype.Text        `json:"wheelplan"`
	AutomatedVehicle             pgtype.Bool        `json:"automated_vehicle"`
	MarkedForExport              pgtype.Bool        `json:"marked_for_export"`
	DateOfLastV5cIssued          pgtype.Date        `json:"date_of_last_v5c_issued"`
	ArtEndDate                   pgtype.Date        `json:"art_end_date"`
	DvlaDataFetchedAt            pgtype.Timestamptz `json:"dvla_data_fetched_at"`
	CreatedAt                    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                    pgtype.Timestamptz `json:"updated_at"`
	UserName                     string             `json:"user_name"`
	UserEmail                    string             `json:"user_email"`
}

func (q *Queries) GetAllCarsWithUsers(ctx context.Context) ([]GetAllCarsWithUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllCarsWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCarsWithUsersRow
	for rows.Next() {
		var i GetAllCarsWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RegistrationNumber,
			&i.Make,
			&i.Colour,
			&i.FuelType,
			&i.EngineCapacity,
			&i.YearOfManufacture,
			&i.MonthOfFirstRegistration,
			&i.MonthOfFirstDvlaRegistration,
			&i.TaxStatus,
			&i.TaxDueDate,
			&i.MotStatus,
			&i.MotExpiryDate,
			&i.Co2Emissions,
			&i.EuroStatus,
			&i.RealDrivingEmissions,
			&i.RevenueWeight,
			&i.TypeApproval,
			&i.Wheelplan,
			&i.AutomatedVehicle,
			&i.MarkedForExport,
			&i.DateOfLastV5cIssued,
			&i.ArtEndDate,
			&i.DvlaDataFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email, password_hash, phone, is_admin, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, pending_email, email_change_token, email_change_expires, created_at FROM users ORDER BY name
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.Phone,
			&i.IsAdmin,
			&i.EmailVerified,
			&i.EmailVerificationToken,
			&i.EmailVerificationExpires,
			&i.PasswordResetToken,
			&i.PasswordResetExpires,
			&i.PendingEmail,
			&i.EmailChangeToken,
			&i.EmailChangeExpires,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsByID = `-- name: GetAppointmentsByID :one
SELECT id, user_id, car_id, datetime, title, description, status, created_at FROM appointments WHERE id = $1
`

func (q *Queries) GetAppointmentsByID(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentsByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CarID,
		&i.Datetime,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAppointmentsForCar = `-- name: GetAppointmentsForCar :many
SELECT id, user_id, car_id, datetime, title, description, status, created_at FROM appointments WHERE car_id = $1 ORDER BY datetime DESC
`

func (q *Queries) GetAppointmentsForCar(ctx context.Context, carID pgtype.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, getAppointmentsForCar, carID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CarID,
			&i.Datetime,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointmentsForUser = `-- name: GetAppointmentsForUser :many
SELECT
  a.id, a.user_id, a.car_id, a.datetime, a.title, a.description, a.status, a.created_at,
  c.registration_number AS car_registration,
  c.make AS car_make,
  c.colour AS car_colour
FROM appointments a
LEFT JOIN cars c ON a.car_id = c.id
WHERE a.user_id = $1
ORDER BY a.datetime DESC
`

type GetAppointmentsForUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CarID           pgtype.UUID        `json:"car_id"`
	Datetime        pgtype.Timestamptz `json:"datetime"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CarRegistration pgtype.Text        `json:"car_registration"`
	CarMake         pgtype.Text        `json:"car_make"`
	CarColour       pgtype.Text        `json:"car_colour"`
}

func (q *Queries) GetAppointmentsForUser(ctx context.Context, userID pgtype.UUID) ([]GetAppointmentsForUserRow, error) {
	rows, err := q.db.Query(ctx, getAppointmentsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAppointmentsForUserRow
	for rows.Next() {
		var i GetAppointmentsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CarID,
			&i.Datetime,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.CarRegistration,
			&i.CarMake,
			&i.CarColour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCarByID = `-- name: GetCarByID :one
SELECT id, user_id, registration_number, make, colour, fuel_type, engine_capacity, year_of_manufacture, month_of_first_registration, month_of_first_dvla_registration, tax_status, tax_due_date, mot_status, mot_expiry_date, co2_emissions, euro_status, real_driving_emissions, revenue_weight, type_approval, wheelplan, automated_vehicle, marked_for_export, date_of_last_v5c_issued, art_end_date, dvla_data_fetched_at, created_at, updated_at FROM cars WHERE id = $1
`

func (q *Queries) GetCarByID(ctx context.Context, id pgtype.UUID) (Car, error) {
	row := q.db.QueryRow(ctx, getCarByID, id)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RegistrationNumber,
		&i.Make,
		&i.Colour,
		&i.FuelType,
		&i.EngineCapacity,
		&i.YearOfManufacture,
		&i.MonthOfFirstRegistration,
		&i.MonthOfFirstDvlaRegistration,
		&i.TaxStatus,
		&i.TaxDueDate,
		&i.MotStatus,
		&i.MotExpiryDate,
		&i.Co2Emissions,
		&i.EuroStatus,
		&i.RealDrivingEmissions,
		&i.RevenueWeight,
		&i.TypeApproval,
		&i.Wheelplan,
		&i.AutomatedVehicle,
		&i.MarkedForExport,
		&i.DateOfLastV5cIssued,
		&i.ArtEndDate,
		&i.DvlaDataFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCarByRegistration = `-- name: GetCarByRegistration :one
SELECT id, user_id, registration_number, make, colour, fuel_type, engine_capacity, year_of_manufacture, month_of_first_registration, month_of_first_dvla_registration, tax_status, tax_due_date, mot_status, mot_expiry_date, co2_emissions, euro_status, real_driving_emissions, revenue_weight, type_approval, wheelplan, automated_vehicle, marked_for_export, date_of_last_v5c_issued, art_end_date, dvla_data_fetched_at, created_at, updated_at FROM cars WHERE registration_number = $1
`

func (q *Queries) GetCarByRegistration(ctx context.Context, registrationNumber string) (Car, error) {
	row := q.db.QueryRow(ctx, getCarByRegistration, registrationNumber)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RegistrationNumber,
		&i.Make,
		&i.Colour,
		&i.FuelType,
		&i.EngineCapacity,
		&i.YearOfManufacture,
		&i.MonthOfFirstRegistration,
		&i.MonthOfFirstDvlaRegistration,
		&i.TaxStatus,
		&i.TaxDueDate,
		&i.MotStatus,
		&i.MotExpiryDate,
		&i.Co2Emissions,
		&i.EuroStatus,
		&i.RealDrivingEmissions,
		&i.RevenueWeight,
		&i.TypeApproval,
		&i.Wheelplan,
		&i.AutomatedVehicle,
		&i.MarkedForExport,
		&i.DateOfLastV5cIssued,
		&i.ArtEndDate,
		&i.DvlaDataFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCarsByUserID = `-- name: GetCarsByUserID :many
SELECT id, user_id, registration_number, make, colour, fuel_type, engine_capacity, year_of_manufacture, month_of_first_registration, month_of_first_dvla_registration, tax_status, tax_due_date, mot_status, mot_expiry_date, co2_emissions, euro_status, real_driving_emissions, revenue_weight, type_approval, wheelplan, automated_vehicle, marked_for_export, date_of_last_v5c_issued, art_end_date, dvla_data_fetched_at, created_at, updated_at FROM cars WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetCarsByUserID(ctx context.Context, userID pgtype.UUID) ([]Car, error) {
	rows, err := q.db.Query(ctx, getCarsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Car
	for rows.Next() {
		var i Car
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RegistrationNumber,
			&i.Make,
			&i.Colour,
			&i.FuelType,
			&i.EngineCapacity,
			&i.YearOfManufacture,
			&i.MonthOfFirstRegistration,
			&i.MonthOfFirstDvlaRegistration,
			&i.TaxStatus,
			&i.TaxDueDate,
			&i.MotStatus,
			&i.MotExpiryDate,
			&i.Co2Emissions,
			&i.EuroStatus,
			&i.RealDrivingEmissions,
			&i.RevenueWeight,
			&i.TypeApproval,
			&i.Wheelplan,
			&i.AutomatedVehicle,
			&i.MarkedForExport,
			&i.DateOfLastV5cIssued,
			&i.ArtEndDate,
			&i.DvlaDataFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextAppointmentForCar = `-- name: GetNextAppointmentForCar :one
SELECT id, user_id, car_id, datetime, title, description, status, created_at FROM appointments
WHERE car_id = $1 AND datetime > NOW() AND status != 'cancelled'
ORDER BY datetime ASC
LIMIT 1
`

func (q *Queries) GetNextAppointmentForCar(ctx context.Context, carID pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getNextAppointmentForCar, carID)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CarID,
		&i.Datetime,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, phone, is_admin, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, pending_email, email_change_token, email_change_expires, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.PendingEmail,
		&i.EmailChangeToken,
		&i.EmailChangeExpires,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailChangeToken = `-- name: GetUserByEmailChangeToken :one
SELECT id, name, email, password_hash, phone, is_admin, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, pending_email, email_change_token, email_change_expires, created_at FROM users WHERE email_change_token = $1 AND email_change_expires > NOW()
`

func (q *Queries) GetUserByEmailChangeToken(ctx context.Context, emailChangeToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailChangeToken, emailChangeToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.PendingEmail,
		&i.EmailChangeToken,
		&i.EmailChangeExpires,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, phone, is_admin, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, pending_email, email_change_token, email_change_expires, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.PendingEmail,
		&i.EmailChangeToken,
		&i.EmailChangeExpires,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPasswordResetToken = `-- name: GetUserByPasswordResetToken :one
SELECT id, name, email, password_hash, phone, is_admin, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, pending_email, email_change_token, email_change_expires, created_at FROM users WHERE password_reset_token = $1 AND password_reset_expires > NOW()
`

func (q *Queries) GetUserByPasswordResetToken(ctx context.Context, passwordResetToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPasswordResetToken, passwordResetToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.PendingEmail,
		&i.EmailChangeToken,
		&i.EmailChangeExpires,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, name, email, password_hash, phone, is_admin, email_verified, email_verification_token, email_verification_expires, password_reset_token, password_reset_expires, pending_email, email_change_token, email_change_expires, created_at FROM users WHERE email_verification_token = $1 AND email_verification_expires > NOW()
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, emailVerificationToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, emailVerificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.EmailVerified,
		&i.EmailVerificationToken,
		&i.EmailVerificationExpires,
		&i.PasswordResetToken,
		&i.PasswordResetExpires,
		&i.PendingEmail,
		&i.EmailChangeToken,
		&i.EmailChangeExpires,
		&i.CreatedAt,
	)
	return i, err
}

const isTokenBlacklisted = `-- name: IsTokenBlacklisted :one
SELECT EXISTS(SELECT 1 FROM token_blacklist WHERE token_hash = $1 AND expires_at > NOW())
`

func (q *Queries) IsTokenBlacklisted(ctx context.Context, tokenHash string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenBlacklisted, tokenHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const makeUserAdmin = `-- name: MakeUserAdmin :exec
UPDATE users SET is_admin = TRUE WHERE email = $1
`

func (q *Queries) MakeUserAdmin(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, makeUserAdmin, email)
	return err
}

const removeUserAdmin = `-- name: RemoveUserAdmin :exec
UPDATE users SET is_admin = FALSE WHERE email = $1
`

func (q *Queries) RemoveUserAdmin(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, removeUserAdmin, email)
	return err
}

const resetPassword = `-- name: ResetPassword :exec
UPDATE users SET password_hash = $2, password_reset_token = NULL, password_reset_expires = NULL WHERE id = $1
`

type ResetPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) error {
	_, err := q.db.Exec(ctx, resetPassword, arg.ID, arg.PasswordHash)
	return err
}

const setEmailChangeRequest = `-- name: SetEmailChangeRequest :exec
UPDATE users SET pending_email = $2, email_change_token = $3, email_change_expires = $4 WHERE id = $1
`

type SetEmailChangeRequestParams struct {
	ID                 pgtype.UUID        `json:"id"`
	PendingEmail       pgtype.Text        `json:"pending_email"`
	EmailChangeToken   pgtype.Text        `json:"email_change_token"`
	EmailChangeExpires pgtype.Timestamptz `json:"email_change_expires"`
}

func (q *Queries) SetEmailChangeRequest(ctx context.Context, arg SetEmailChangeRequestParams) error {
	_, err := q.db.Exec(ctx, setEmailChangeRequest,
		arg.ID,
		arg.PendingEmail,
		arg.EmailChangeToken,
		arg.EmailChangeExpires,
	)
	return err
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :exec
UPDATE users SET password_reset_token = $2, password_reset_expires = $3 WHERE email = $1
`

type SetPasswordResetTokenParams struct {
	Email                string             `json:"email"`
	PasswordResetToken   pgtype.Text        `json:"password_reset_token"`
	PasswordResetExpires pgtype.Timestamptz `json:"password_reset_expires"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetToken, arg.Email, arg.PasswordResetToken, arg.PasswordResetExpires)
	return err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :exec
UPDATE appointments SET status = $2 WHERE id = $1
`

type UpdateAppointmentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAppointmentStatus, arg.ID, arg.Status)
	return err
}

const updateCarDVLAData = `-- name: UpdateCarDVLAData :one
UPDATE cars SET
    make = $2,
    colour = $3,
    fuel_type = $4,
    engine_capacity = $5,
    year_of_manufacture = $6,
    month_of_first_registration = $7,
    month_of_first_dvla_registration = $8,
    tax_status = $9,
    tax_due_date = $10,
    mot_status = $11,
    mot_expiry_date = $12,
    co2_emissions = $13,
    euro_status = $14,
    real_driving_emissions = $15,
    revenue_weight = $16,
    type_approval = $17,
    wheelplan = $18,
    automated_vehicle = $19,
    marked_for_export = $20,
    date_of_last_v5c_issued = $21,
    art_end_date = $22,
    dvla_data_fetched_at = $23,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, registration_number, make, colour, fuel_type, engine_capacity, year_of_manufacture, month_of_first_registration, month_of_first_dvla_registration, tax_status, tax_due_date, mot_status, mot_expiry_date, co2_emissions, euro_status, real_driving_emissions, revenue_weight, type_approval, wheelplan, automated_vehicle, marked_for_export, date_of_last_v5c_issued, art_end_date, dvla_data_fetched_at, created_at, updated_at
`

type UpdateCarDVLADataParams struct {
	ID                           pgtype.UUID        `json:"id"`
	Make                         pgtype.Text        `json:"make"`
	Colour                       pgtype.Text        `json:"colour"`
	FuelType                     pgtype.Text        `json:"fuel_type"`
	EngineCapacity               pgtype.Int4        `json:"engine_capacity"`
	YearOfManufacture            pgtype.Int4        `json:"year_of_manufacture"`
	MonthOfFirstRegistration     pgtype.Text        `json:"month_of_first_registration"`
	MonthOfFirstDvlaRegistration pgtype.Text        `json:"month_of_first_dvla_registration"`
	TaxStatus                    pgtype.Text        `json:"tax_status"`
	TaxDueDate                   pgtype.Date        `json:"tax_due_date"`
	MotStatus                    pgtype.Text        `json:"mot_status"`
	MotExpiryDate                pgtype.Date        `json:"mot_expiry_date"`
	Co2Emissions                 pgtype.Int4        `json:"co2_emissions"`
	EuroStatus                   pgtype.Text        `json:"euro_status"`
	RealDrivingEmissions         pgtype.Text        `json:"real_driving_emissions"`
	RevenueWeight                pgtype.Int4        `json:"revenue_weight"`
	TypeApproval                 pgtype.Text        `json:"type_approval"`
	Wheelplan                    pgtype.Text        `json:"wheelplan"`
	AutomatedVehicle             pgtype.Bool        `json:"automated_vehicle"`
	MarkedForExport              pgtype.Bool        `json:"marked_for_export"`
	DateOfLastV5cIssued          pgtype.Date        `json:"date_of_last_v5c_issued"`
	ArtEndDate                   pgtype.Date        `json:"art_end_date"`
	DvlaDataFetchedAt            pgtype.Timestamptz `json:"dvla_data_fetched_at"`
}

func (q *Queries) UpdateCarDVLAData(ctx context.Context, arg UpdateCarDVLADataParams) (Car, error) {
	row := q.db.QueryRow(ctx, updateCarDVLAData,
		arg.ID,
		arg.Make,
		arg.Colour,
		arg.FuelType,
		arg.EngineCapacity,
		arg.YearOfManufacture,
		arg.MonthOfFirstRegistration,
		arg.MonthOfFirstDvlaRegistration,
		arg.TaxStatus,
		arg.TaxDueDate,
		arg.MotStatus,
		arg.MotExpiryDate,
		arg.Co2Emissions,
		arg.EuroStatus,
		arg.RealDrivingEmissions,
		arg.RevenueWeight,
		arg.TypeApproval,
		arg.Wheelplan,
		arg.AutomatedVehicle,
		arg.MarkedForExport,
		arg.DateOfLastV5cIssued,
		arg.ArtEndDate,
		arg.DvlaDataFetchedAt,
	)
	var i Car
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RegistrationNumber,
		&i.Make,
		&i.Colour,
		&i.FuelType,
		&i.EngineCapacity,
		&i.YearOfManufacture,
		&i.MonthOfFirstRegistration,
		&i.MonthOfFirstDvlaRegistration,
		&i.TaxStatus,
		&i.TaxDueDate,
		&i.MotStatus,
		&i.MotExpiryDate,
		&i.Co2Emissions,
		&i.EuroStatus,
		&i.RealDrivingEmissions,
		&i.RevenueWeight,
		&i.TypeApproval,
		&i.Wheelplan,
		&i.AutomatedVehicle,
		&i.MarkedForExport,
		&i.DateOfLastV5cIssued,
		&i.ArtEndDate,
		&i.DvlaDataFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $2 WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const userCancelAppointment = `-- name: UserCancelAppointment :exec
UPDATE appointments SET status = 'cancelled' WHERE id = $1 AND user_id = $2
`

type UserCancelAppointmentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UserCancelAppointment(ctx context.Context, arg UserCancelAppointmentParams) error {
	_, err := q.db.Exec(ctx, userCancelAppointment, arg.ID, arg.UserID)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users SET email_verified = TRUE, email_verification_token = NULL, email_verification_expires = NULL WHERE id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
